Kill-9-Mockingbird/grace-shopper

- package-lock.json
- package.json
- server/db/models/celebrity.js
- server/db/models/experience.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/user.js
Added Sequelize models and associations.
---
> added sequelize models

- package-lock.json
- package.json
Faker installed + saved to package.json/package-lock.json
> faker installed

- script/celebritiesSeed.json
> celebrities seeded

- script/orderSeed.js
The purpose of this PR is to create the data we will use to fuel our associations between users and experiences.
---
> added orderSeed

- script/seed.js
> minor edits

- server/db/models/user.spec.js
Updated server/db/models/user.spec.js
> test updates

- server/api/users.spec.js
> fixing tests

- client/components/allExperiences.js
- client/components/index.js
- client/routes.js
- client/store/experience.js
- client/store/index.js
- server/api/experiences.js
- server/api/index.js
- server/db/models/index.js
* added all experiences and single experience route
*added all experiences component
*added reducer for all experiences and single experience
added all experiences and single experience route
added all experiences component
added reducer for all experiences and single experience
---
need to do eagerloading for API route to show celebrity.
> allexperiences component

- client/app.js
- client/components/navbar.js
- client/components/signup-form.js
- public/style.css
- server/db/models/user.js
Working on form
Updated user model
> form component in progress

- client/components/allExperiences.js
- git.js
- script/experiencesSeed.js
- server/api/users.js
- server/db/models/index.js
> User route

- script/experiencesSeed.js
- script/orderSeed.js
- script/userSeed.js
- server/db/models/celebrity.js
Added faker.seed(123) to seed files that used faker. Now we will have consistent random data every time we seed the database.
> made consistent seeded data

- client/components/singleExperience.js
- client/store/experience.js
Fixed bug in single experience and got host name to render on the front end. 
This pull request would fulfill the requirements of showing all products and single product on the deployed website.
> completed single experience

- client/app.js
- script/experiencesSeed.js
- script/orderDetailSeed.js
- script/orderSeed.js
- script/seed.js
- script/userSeed.js
- server/api/experiences.js
- server/api/users.js
- server/db/models/experience.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/orderDetail.js
- server/db/models/user.js
Created through table for order details.
---
> seed fixes

- client/app.js
- client/components/auth-form.js
- client/store/user.js
- server/db/models/user.js
Can log-in using email, can create new user. Validation checks if email already exists in db and denies new user creation if there is.
> Functional User Form

- utils.js
> added utils file

- schema.txt
- script/userSeed.js
- server/api/users.js
- server/api/users.spec.js
- server/db/models/user.js
- server/db/models/user.spec.js
> deleted username from db

- client/components/cart.js
- client/store/cart.js
- server/api/cart.js
- server/db/models/index.js
> delete item + add item

- client/components/cart.js
- client/store/cart.js
- server/api/cart.js
Combining updating cart with add + delete cart functions
> partial functionality with updatingCartQuantity

- client/components/admin-all-users.js
- client/components/carousel.js
- client/components/cart.js
- client/components/cartItems.js
- client/components/singleExperience.js
- client/components/user-home.js
- client/routes.js
- client/store/admins.js
- client/store/cart.js
- client/store/index.js
- client/store/orders.js
- public/index.html
- public/style.css
- script/userSeed.js
- server/api/admins.js
- server/api/cart.js
- server/api/index.js
- server/api/users.js
- server/auth/google.js
- server/db/models/index.js
- server/db/models/orderDetail.js
- server/db/models/user.js
> Admin routes

- client/components/cart.js
- client/components/cartItems.js
- client/components/exp-list.js
- client/components/singleExperience.js
- client/store/cart.js
- public/style.css
- script/experiencesSeed.js
- server/api/cart.js
> tried really hard to debug. could not. css updates

- client/components/auth-form.js
- client/components/singleExperience.js
- public/style.css
> styling changes

- client/app.js
- client/components/cartItems.js
- client/routes.js
- client/store/cart.js
- server/api/cart.js
Add feature is fully functional.
> fully functional add to cart feature

- client/routes.js
> client routes

- client/app.js
- client/components/user-home.spec.js
- server/api/admins.js
- server/api/admins.spec.js
- server/api/experiences.spec.js
- server/api/users.js
- server/api/users.spec.js
- server/db/models/associations.spec.js
- server/db/models/experience.spec.js
- server/db/models/index.js
- server/db/models/order.spec.js
added test specs for admin, experience and user routes
added test specs for user, experience, order models as well as associations
fixed existing tests to make sure all are passing 
made some minor edits (mainly cosmetic changes e.g. unused variables)
travis build passed as all 21 test specs are passing.
> added tests for backend components and some minor edits

- client/components/cart.js
- client/components/cartItems.js
- client/components/singleExperience.js
- client/store/cart.js
- public/index.html
- public/style.css
- server/api/cart.js
#14 Incrementing and decrementing qty in cart completed. Also, add item and delete item is finished. :)
> increment/decrement, delete, and add feature completed

- client/components/cart.js
- client/store/cart.js
added increment/decrement quantity for guest cart feature
> added increment/decrement item for guest feature

- client/store/cart.js
- server/api/cart.js
merged user and guest cart for logged in users
> merged user and guest cart for loggedin users

- client/components/cart.js
- client/components/cartItems.js
This pr added cart totals to the rendering of the cart and cart item component.
---
> order totals

- client/components/cart.js
- client/store/cart.js
added order total for guest cart 
fixed adding to guest cart
> fixed guest cart

- client/components/cart.js
- script/experiencesSeed.js
> some cleanup and bug fixes

- client/components/Review.js
> updated prices in review

- client/components/carousel.js
> home screen shop now fix

- client/components/Checkout.js
- client/components/Review.js
- client/components/cart.js
> checkout fix
